name: 'nsite Action'
description: 'Deploys static website files to Blossom/Nostr using the nsyte CLI.'
author: 'nsite-action Developers' # Placeholder

inputs:
  nsyte_version:
    description: 'The version of the nsyte CLI to use (e.g., "v0.5.3", "latest"). Needs to match a tag in github.com/sandwichfarm/nsyte/releases'
    required: false
    default: 'latest'
  nbunksec:
    description: 'The nbunksec string for authentication via NIP-46 bunker. Store this as a GitHub Secret.'
    required: true
  directory:
    description: 'The directory containing the static files to upload.'
    required: true
  relays:
    description: 'Array of Nostr relay WebSocket URIs to publish the site event to. Passed as a YAML array.'
    required: true
  servers:
    description: 'Array of Blossom server WebSocket URIs to upload files to. Passed as a YAML array.'
    required: true
  force:
    description: 'Corresponds to the --force flag in nsyte upload. Re-upload all files.'
    required: false
    default: 'false'
  purge:
    description: 'Corresponds to the --purge flag in nsyte upload. Delete remote files not present locally.'
    required: false
    default: 'false'
  verbose:
    description: 'Corresponds to the --verbose flag in nsyte upload. Show detailed output.'
    required: false
    default: 'false'
  concurrency:
    description: 'Corresponds to the --concurrency flag in nsyte upload. Number of parallel uploads.'
    required: false
    default: '4'
  fallback:
    description: 'Corresponds to the --fallback flag in nsyte upload. Path to the fallback HTML file (e.g., /index.html for SPAs).'
    required: false
    default: ''

outputs:
  status:
    description: 'Status of the upload operation (e.g., "success").'
  nsyte_version_used:
    description: 'The actual version of nsyte that was downloaded and used.'

branding:
  icon: 'upload-cloud'
  color: 'purple'

runs:
  using: 'composite'
  steps:
    - name: Determine Platform
      id: platform
      shell: bash
      run: |
        PLATFORM=""
        EXE_SUFFIX=""
        if [[ "${{ runner.os }}" == "Linux" ]]; then PLATFORM="linux";
        elif [[ "${{ runner.os }}" == "macOS" ]]; then PLATFORM="macos";
        elif [[ "${{ runner.os }}" == "Windows" ]]; then PLATFORM="windows"; EXE_SUFFIX=".exe";
        else echo "::error::Unsupported runner OS: ${{ runner.os }}"; exit 1; fi
        echo "Detected platform: $PLATFORM"
        echo "platform=$PLATFORM" >> $GITHUB_OUTPUT
        echo "exe_suffix=$EXE_SUFFIX" >> $GITHUB_OUTPUT

    - name: Set nsyte Version
      id: version
      shell: bash
      run: |
        NSYT_VERSION_INPUT="${{ inputs.nsyte_version }}"
        NSYT_VERSION_FINAL=""
        VERSION_NUMBER=""
        if [[ "$NSYT_VERSION_INPUT" == "latest" ]]; then
          echo "Input version is 'latest', resolving..."
          LATEST_TAG=""
          # Try GH CLI first if available and authenticated, using version sort
          if command -v gh &> /dev/null && gh auth status &> /dev/null; then
            echo "Using 'gh' CLI to find latest semantic version release."
            # Get all release tags, filter for those starting with v<digit> (to avoid non-version tags),
            # sort them using version sort (-V), and take the last one.
            LATEST_TAG=$(gh release list -R sandwichfarm/nsyte --json tagName --jq '.[].tagName' 2>/dev/null | grep '^v[0-9]' | sort -V | tail -n 1)
          fi
          # Fallback to curl if GH CLI failed, not available/authed, or returned no tag
          if [[ -z "$LATEST_TAG" ]]; then 
            echo "Using GitHub API (curl) to find latest release (gh CLI failed or sort -V might not be available/effective)."
            # This API endpoint gets the release marked as "latest" in the UI.
            # If that's not updated, this will also be outdated.
            # A more complex curl/jq/sort would be needed for true semantic latest via API without gh.
            LATEST_TAG=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/sandwichfarm/nsyte/releases/latest | grep -o '"tag_name": *"[^"]*"' | cut -d '"' -f 4)
            if [[ -z "$LATEST_TAG" || "$LATEST_TAG" == "null" ]]; then 
                 # As a very last resort if /releases/latest gives nothing, try getting all and picking first (newest created)
                 echo "/releases/latest endpoint gave no result, trying to get the most recently created release from the full list."
                 LATEST_TAG=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/sandwichfarm/nsyte/releases | jq -r '.[0].tag_name' 2>/dev/null)
            fi
          fi
          if [[ -z "$LATEST_TAG" || "$LATEST_TAG" == "null" ]]; then echo "::error::Failed to determine latest nsyte release tag."; exit 1; fi
          NSYT_VERSION_FINAL="$LATEST_TAG"
          echo "Resolved latest version: $NSYT_VERSION_FINAL"
        else
          NSYT_VERSION_FINAL="${{ inputs.nsyte_version }}"
          echo "Using specified version: $NSYT_VERSION_FINAL"
        fi
        # Extract version number for asset filename
        if [[ "$NSYT_VERSION_FINAL" =~ ^v(.+)$ ]]; then VERSION_NUMBER="${BASH_REMATCH[1]}"; else VERSION_NUMBER="$NSYT_VERSION_FINAL"; fi
        echo "Using nsyte tag: $NSYT_VERSION_FINAL (version number for asset: $VERSION_NUMBER)"
        echo "version=$NSYT_VERSION_FINAL" >> $GITHUB_OUTPUT
        echo "version_number=$VERSION_NUMBER" >> $GITHUB_OUTPUT

    - name: Download nsyte
      id: download_nsyte 
      shell: bash
      run: |
        VERSION_TAG="${{ steps.version.outputs.version }}"
        VERSION_NUMBER="${{ steps.version.outputs.version_number }}"
        PLATFORM="${{ steps.platform.outputs.platform }}"
        EXE_SUFFIX="${{ steps.platform.outputs.exe_suffix }}"
        ASSET_FILENAME="nsyte-$PLATFORM-$VERSION_NUMBER$EXE_SUFFIX"
        DOWNLOAD_URL="https://github.com/sandwichfarm/nsyte/releases/download/$VERSION_TAG/$ASSET_FILENAME"
        echo "Downloading nsyte $ASSET_FILENAME from $DOWNLOAD_URL"
        mkdir -p nsyte_bin 
        HTTP_STATUS=$(curl -sL -w "%{http_code}" -o "nsyte_bin/$ASSET_FILENAME" "$DOWNLOAD_URL")
        if [[ "$HTTP_STATUS" != "200" ]]; then
          echo "::error::Failed to download $ASSET_FILENAME (HTTP Status: $HTTP_STATUS)."
          echo "Please check if version '$VERSION_TAG' and asset '$ASSET_FILENAME' exist for platform '$PLATFORM'."
          
          if command -v gh &> /dev/null && gh auth status &> /dev/null; then
            gh release view "$VERSION_TAG" -R sandwichfarm/nsyte --json assets --jq '.assets[].name' 2>/dev/null || echo "(Could not list assets with gh CLI)"
          else 
            curl -s "https://api.github.com/repos/sandwichfarm/nsyte/releases/tags/$VERSION_TAG" | grep '"name":' | cut -d '"' -f 4 || echo "(Could not list assets with API)"
          fi
          exit 1
        fi
        chmod +x "nsyte_bin/$ASSET_FILENAME"
        echo "nsyte_path=$(pwd)/nsyte_bin/$ASSET_FILENAME" >> $GITHUB_OUTPUT

    - name: Build nsyte command
      id: build_cmd
      shell: bash
      run: |
        CMD="\"${{ steps.download_nsyte.outputs.nsyte_path }}\" upload \"${{ inputs.directory }}\" --nbunksec \"${{ inputs.nbunksec }}\""
        
        RELAYS_INPUT="${{ inputs.relays }}"
        if [[ -n "$RELAYS_INPUT" ]]; then
          RELAYS_CSV=$(echo "$RELAYS_INPUT" | tr '\n' ',' | sed 's/,$//g' | sed 's/\r//g')
          if [[ -n "$RELAYS_CSV" ]]; then
             CMD+=" --relays \"$RELAYS_CSV\""
          fi
        fi

        SERVERS_INPUT="${{ inputs.servers }}"
        if [[ -n "$SERVERS_INPUT" ]]; then
          SERVERS_CSV=$(echo "$SERVERS_INPUT" | tr '\n' ',' | sed 's/,$//g' | sed 's/\r//g')
          if [[ -n "$SERVERS_CSV" ]]; then
            CMD+=" --servers \"$SERVERS_CSV\""
          fi
        fi

        if [[ "${{ inputs.force }}" == "true" ]]; then CMD+=" --force"; fi
        if [[ "${{ inputs.purge }}" == "true" ]]; then CMD+=" --purge"; fi
        if [[ "${{ inputs.verbose }}" == "true" ]]; then CMD+=" --verbose"; fi
        if [[ -n "${{ inputs.fallback }}" ]]; then CMD+=" --fallback \"${{ inputs.fallback }}\""; fi
        if [[ -n "${{ inputs.concurrency }}" ]]; then CMD+=" --concurrency ${{ inputs.concurrency }}"; fi
        echo "command=$CMD" >> $GITHUB_OUTPUT

    - name: Run nsyte upload
      id: nsyte_run
      shell: bash
      run: |
        NSYT_COMMAND="${{ steps.build_cmd.outputs.command }}"
        echo "Executing nsyte command (secrets masked):"
        
        MASKED_COMMAND=$(echo "$NSYT_COMMAND" | \
          sed -e "s/--nbunksec \"[^\"]*\"/--nbunksec \"***MASKED***\"/" \
              -e "s/--relays \"[^\"]*\"/--relays \"***MASKED***\"/" \
              -e "s/--servers \"[^\"]*\"/--servers \"***MASKED***\"/")
        echo "$MASKED_COMMAND"
        
        
        if eval "$NSYT_COMMAND"; then
           echo "nsyte upload completed successfully."
           echo "status=success" >> $GITHUB_OUTPUT
        else
           echo "::error::nsyte upload command failed with exit code $?."
           echo "status=failure" >> $GITHUB_OUTPUT
           exit 1
        fi
        echo "nsyte_version_used=${{ steps.version.outputs.version }}" >> $GITHUB_OUTPUT 